### PR TITLE
modified html

### PR DESCRIPTION
**Pull request by rdubel**
s'il vous plait làààà

### CODE REVIEW

**Comment by bl00m** [comment]
no

**Comment by rdubel** [comment]
c'mon there is no clonflicts

**Comment by rdubel** [comment]
don't be like that

**Comment by rdubel** [comment]
thanks brah

**Comment by rdubel** [comment]
pls lel

**Comment by bl00m** [comment]
Stop harassing me

**Comment by rdubel** [comment]
I'm not, i'm just politely asking :(

**Comment by rdubel** [comment]
be my friend lel :dagger:

**Comment by bl00m** [comment]
I think you're to rude

**Comment by bl00m** [comment]
I don't want to be you're partner no more

**Comment by bl00m** [comment]
I think we should break

**Comment by rdubel** [comment]
Okay, well, fine ! So be it !

**Comment by rdubel** [comment]
But let me tell you one thing : You'll regret it, for sure !

**Comment by bl00m** [comment]
The oposite is true

**Pull request merged**
